### ISSUE TITLE
Planting Clutter seeds causes crash

### ISSUE THREAD

**Issue by SirSquill** [EmilsGithub/Clutter-Mod-Repository#1]
[crash-2023-06-11_16.23.16-client.txt](https://github.com/EmilsGithub/Clutter-Mod-Repository/files/11715675/crash-2023-06-11_16.23.16-client.txt)
Mc version 1.20 / fabric loader 0.14.21 / Clutter 0.3.2 / GeckoLib 4.2 

Upon planting any seed from the clutter mod the game immediately crashes. Vanilla seeds are fine. I am using the Fabric Seasons mod as well, that's the only thing I can think of that would conflict. 

Crash log above^^^

**Comment by SirSquill** [comment]
EDIT: Upon the removal of Fabric Season the crash still persists. Cotton and hops seeds cause crashes when planting.
Updated Log: 
[crash-2023-06-11_23.09.29-client.txt](https://github.com/EmilsGithub/Clutter-Mod-Repository/files/11717151/crash-2023-06-11_23.09.29-client.txt)

**Comment by EmilsGithub** [comment]
Must be a problem with updating to 1.20...
I'll look into it first thing when I come home from work today.

**Comment by EmilsGithub** [comment]
Found the error, resolved it, update will be out shortly.
