### ISSUE TITLE
[Suggestion] Compat for bowl/mug

### ISSUE THREAD

**Issue by Ultimushadow** [EmilsGithub/Clutter-Mod-Repository#10]
I'm a sucker for anything that allows player to put food down as an item since we don't get a lot of that kind of thing even with other food mods. I think that the bowl and mug are good options for a kind of universal "put food down" if you're up for adding compatibility for them. I'm currently using the Enhancer mod and it revamps the vanilla stew items, which are a little better than the vanilla versions but named the same thing so at the very least it would be nice to get those in. I was thinking the mug would be nice for more liquids as well, even if it's just the vanilla ones, but milk/water/potions would be fun to see in there! You could also put in compat for other mods as well for that one. 
When you added these in, did you make the textures by hand or were they data driven? While making them by hand probably wouldn't take that long, I imagine especially for things like potions it would be easier to use some kind of library to drive the potion coloring

**Comment by EmilsGithub** [comment]
All the textures are made by hand. I don't really plan on doing anything more with the bowl, I did like the sound of adding milk though.

Other ways for the player to put food down are planned (plates for example). And maybe placeable bottles and other things.

**Comment by Ultimushadow** [comment]
In that case, is it possible to add a config to add items to be accepted, and link it to a texture that could be added via resource pack? aka put in "modname:item" then link the texture to "clutter/textures/bowlcompat/modname/item.png" or something. That way you could offload that compatibility to people like me who are willing to make the textures to share with people? One of the things I see with a lot of mods is that most of them require some work in order to fit together, so I understand if this is outside your scope for the mod, but if you were to add something like that I could start sharing compats for some of the mods I'm using and more people could enjoy easier connectivity!

Placeable bottles would be awesome, and being able to place food on plates is always a great touch for decorating. For the latter, are you thinking of just a standard 2d item render or a 3d model? I imagine the latter would be much more work texture wise and would definitely alienate other mods but it could be an interesting addition

**Comment by EmilsGithub** [comment]
Adding the ability to add more textures / variants via config & resource packs would be waaaaaaay too much work for such a small feature, would take less time for me to just manually add everything (I won't do it). 

As for the plates I was thinking a blockentity renderer so that any "food item" would be placeable on the plate, even modded ones. (Basically the same way that items in the players hand(s) are rendered, not completely 2D but not really 3D).

**Comment by Ultimushadow** [comment]
Gotcha, well thanks for having a look at the suggestion anyways! I may try to add it in myself, if I do I'll share it here
