### ISSUE TITLE
Github 1.19.2 branch isn't up to date

### ISSUE THREAD

**Issue by jozzo402** [EmilsGithub/Clutter-Mod-Repository#11]
At least I can't find any of the changes from 0.2.1 in the sources.

**Comment by EmilsGithub** [comment]
Not an issue, stopped updating 1.19.2 when 1.19.4 released due to the differences between those versions of fabric.

1.19.3 and 1.19.4 are very similar so keeping them both at the same state isn't too annoying.

I now only update the most recent version(s) of minecraft due to time constraints.

**Comment by jozzo402** [comment]
@EmilsGithub That's understandable. Is there any alternative way for me to download the source for the 1.19.2 version? Clutter's items overlap with a few other mods I use so I was looking to remove them.

**Comment by EmilsGithub** [comment]
0.2.1 is the latest version for 1.19.2 is anything missing from that branch?

**Comment by jozzo402** [comment]
@EmilsGithub It looks like the 1.19.2 branch is missing some of the newer items, eg in ModItems.java:
https://github.com/EmilsGithub/Clutter-Mod-Repository/blob/Clutter-1.19.2/src/main/java/net/emilsg/clutter/item/ModItems.java
Compared to the 1.19.3 branch:
https://github.com/EmilsGithub/Clutter-Mod-Repository/blob/Clutter-1.19.3/src/main/java/net/emilsg/clutter/item/ModItems.java

Namely all the coins, even though the coins do exist in the 1.19.2 release of the mod.

**Comment by EmilsGithub** [comment]
All should be there now.

**Comment by jozzo402** [comment]
Yep worked perfectly, thanks!
