### ISSUE TITLE
clutter stops emi sending information from the server to client it seems 

### ISSUE THREAD

**Issue by Taleuxss** [EmilsGithub/Clutter-Mod-Repository#12]
when joining my server with clutter i cannot see the recipes anymore and when removing clutter im able to see them again

**Comment by EmilsGithub** [comment]
Do you have the mod on the server too?

**Comment by Taleuxss** [comment]
yeah

**Comment by EmilsGithub** [comment]
I tried recreatigg the issue and wasn't able to. Do you have a log or something I could look at?
