### ISSUE TITLE
Missing Texture for Sheep Plushie (clutter-1.20.1-0.3.9.jar)

### ISSUE THREAD

**Issue by gamerpotion** [EmilsGithub/Clutter-Mod-Repository#13]
hi, 
There seems to be missing texture issue for the sheep plushie. Not sure if this is a conflict with other plushie mod - https://www.curseforge.com/minecraft/mc-mods/plushie-mod
(using in darkrpg modpack)

<img src="https://media.discordapp.net/attachments/964187610392199209/1135221792273866842/image.png">

<img src="https://media.discordapp.net/attachments/964187610392199209/1135221834695057479/image.png">

**Comment by EmilsGithub** [comment]
Fixed in the next update.
