### ISSUE TITLE
[Suggestion] Sliver Trim Material

### ISSUE THREAD

**Issue by Ultimushadow** [EmilsGithub/Clutter-Mod-Repository#15]
Hey, just a quick suggestion to add silver as a trim material for 1.20+ versions! In fact, I already did this myself in datapack form here: 
[Clutter Silver Trim Resource Pack.zip](https://github.com/EmilsGithub/Clutter-Mod-Repository/files/12234995/Clutter.Silver.Trim.Resource.Pack.zip)
[Clutter Silver Trim Datapack.zip](https://github.com/EmilsGithub/Clutter-Mod-Repository/files/12234996/Clutter.Silver.Trim.Datapack.zip)

I used the palette from the silver ingot texture but in all honestly it looks a bit off. Maybe you could make it a little brighter?
Oh and, this pack automatically compats with More Armor Trims, I'm sure there are other mods that add trims but this is the one I was using so I figured I'd keep it in.

**Comment by EmilsGithub** [comment]
Hi! I have already started adding armor trim materials to the next update, and a new ore will be included as well. So, look forward to it! 😆
