### ISSUE TITLE
[Bug] Candle missing sounds

### ISSUE THREAD

**Issue by Ultimushadow** [EmilsGithub/Clutter-Mod-Repository#18]
Hey, love the new content in the update! I'll be testing some things as I go but I wanted to get one out of the way real quick, the large candles don't make a sound when interacted with flint and steel or fire charges! Regular candles and blocks have the lighting sound but the large candles don't. They at least have the extinguish sound though so it looks like you're good there

**Comment by Ultimushadow** [comment]
Oh, it looks like Big Candles can also be lit underwater for some reason, along with the chandeliers, candelabras and wall candles! Vanilla behavior is that the item is unable to be lit. Also, the other candle based items are also missing their sounds for lighting

**Comment by EmilsGithub** [comment]
Fixed all of this.
