### ISSUE TITLE
Chameleon Doesn't appear when I have shaders on

### ISSUE THREAD

**Issue by dexula** [EmilsGithub/Clutter-Mod-Repository#2]
https://medal.tv/games/minecraft/clips/1erOhJ0R0I9MdG/d1337FFTQEwl?invite=cr-MSxMRTEsNDI0MDg2Mzcs

**Comment by EmilsGithub** [comment]
Yeah sorry, nothing I can do about it really since I'm using geckolib for models/render/animations and that's a problem on their end.
