### ISSUE TITLE
[Suggestion] Lily Pad renewability

### ISSUE THREAD

**Issue by Ultimushadow** [EmilsGithub/Clutter-Mod-Repository#22]
The new Lily Pad items currently have no way to renewably collect them! I have some suggestions here.

Minecraft Lily Pads can be obtained through fishing, as well as the Wandering Trader. This should be turned into a tag instead, which includes the vanilla and all three modded items. 

The Giant Lily Pad, when flowering, should drop a Giant Lily Pad seed. It could also be implemented that using Bonemeal on a flowering Giant Lily Pad will drop a seed item, whatever fits the mod better.

Small Lily Pads I have an additional suggestion for, it would be nice to mimic the way Pink Petals were implemented. Be able to place 1-4 and rotate them as the player desires. This could work by placing the Small Lily Pad item up to four times, as well as using Bonemeal to increase the count by one. Once the block hits 4, any additional Bonemeal just drops a Small Lily Pad item into the world. This would then also function for making them renewable!

**Comment by EmilsGithub** [comment]
Added all of the above, except I did not add a tag, I hardcoded them in.
