### ISSUE TITLE
[Bug] Shelf Item Rotation Inconsistency

### ISSUE THREAD

**Issue by Ultimushadow** [EmilsGithub/Clutter-Mod-Repository#25]
I noticed that items aren't rendered consistently when placed on Shelf blocks, they seem to point one direction when placed north/south and another when places east/west
![2023-08-20_05 53 57](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/35935582/fa88faf1-6cd6-4758-be0a-2588b2425a12)
In the image you can see that the sword points to the right when facing north/south (I'm facing north in the SS), and to the left when facing east/west. This has caused some weirdness, for instance, the chair and bench items are always facing opposite directions, they never face the front at the same time

This is being tested with other mods, so if Clutter isn't causing it please let me know and I will try to find the culprit!

**Comment by EmilsGithub** [comment]
![2023-08-20_13 33 59](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/88748435/6a756d48-4f3c-4f2a-bf4e-f037d5a60832)
Fixed. 👍
