### ISSUE TITLE
[Issue/Conflict] Pat Feature?

### ISSUE THREAD

**Issue by A5ho9999** [EmilsGithub/Clutter-Mod-Repository#26]
It would appear that the newer releases include a Pat/Pet Functions which actually conflicts with a lot of other Mods when Sneak Right-clicking. Including Carry Mods as well simply/easy villagers but as the source code isn't public I can't completely confirm this correctly. Makes this mod rather unusable with many of these others mods without being able to disable this functions

**Comment by EmilsGithub** [comment]
There is a config to disable it.

**Comment by A5ho9999** [comment]
I don't see an option for it within the config

**Comment by EmilsGithub** [comment]
Could it be that you updated the mod without removing the config file? If that's the case, remove it and restart the game.

**Comment by A5ho9999** [comment]
After removing the config and using newly generated, setting to false still doesn't disable the function

Config:
```
greed.with_looting_and_mending=false # Greed compatible with Looting and Mending. default: false
greed.chance.per.level=0.01 # Coin drop chance per level of Greed. default: 0.01
coin.drops.and.loot.gen=true # Coin drops and generation. default: true
meltdown.destroy_blocks=false # Meltdown destroys blocks. default: false
spawn.clutter.mobs=true # Spawn Clutter Mobs. default: true
spawn.butterflies=false # Spawn Butterflies. default: true
spawn.chameleons=true # Spawn Chameleons. default: true
spawn.echofins=true # Spawn Echofins. default: true
spawn.mossblooms=true # Spawn Mossblooms. default: true
spawn.kiwi_birds=true # Spawn Kiwi Birds. default: true
spawn.emperor_penguins=true # Spawn Emperor Penguins. default: true
spawn.beavers=true # Spawn Beavers. default: true
generate.geodes=true # Generate Geodes. default: true
generate.ores=true # Generate Ores. default: true
generate.silver_ore=true # Generate Silver Ore. default: true
generate.foliage=true # Generate Foliage. default: true
pet.mobs=false # Allows players to pet Peaceful and/or Baby mobs by right-clicking them while sneaking, this has a small chance of healing that mob. default: true

**Comment by EmilsGithub** [comment]
Are you on a dedicated server, if so the server also has to disable it.

**Comment by A5ho9999** [comment]
Yes, the server has it disabled

**Comment by EmilsGithub** [comment]
I'll take another look at it after work.

**Comment by A5ho9999** [comment]
Any update on this?

**Comment by EmilsGithub** [comment]
It is resolved and will be fixed next time the mod updates.
