### ISSUE TITLE
Can't repair Butterfly Elytra

### ISSUE THREAD

**Issue by tmprnc** [EmilsGithub/Clutter-Mod-Repository#28]
I am unable to repair my Butterfly Elytra using Phantom Membranes. Is this intentional?

![2023-09-14_17 39 06](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/3785923/11bd535c-bb51-49f1-9323-4f89e2605682)

Running 1.20-0.4.3 on Quilt 0.20.2 for 1.20.1.

**Comment by EmilsGithub** [comment]
Hi, yes it's international.
Use the butterflies in a bottle to repair it.
