### ISSUE TITLE
Coin Duplication Bug

### ISSUE THREAD

**Issue by ZaneFlynt01** [EmilsGithub/Clutter-Mod-Repository#3]
I'm using version 1.20.1-0.3.7

Placing down Copper Coins is duplicating the coins. Have not tested it with Silver or Gold coins.

Video showcasing what I did and what mods I have should be able to be found at https://drive.google.com/file/d/1uEsnd9kXiIwgYX9S4aARTMo5AzC8eRQt/view?usp=sharing

**Comment by EmilsGithub** [comment]
It normally takes 8 coins to place, it's probably one of your other mods that makes it take none. (I'd say the no hunger mod)

**Comment by ZaneFlynt01** [comment]
No, it isn't the hunger mod. I tried loading the mod again later that same day and it worked perfectly fine. I dunno what changed, I didn't change versions, didn't change any sort of config options, nothin.

**Comment by EmilsGithub** [comment]
Changed how placing coins work in the next update, this shouldn't be an issue then.
