### ISSUE TITLE
[Bug] Cherry Chairs Dont catch on fire

### ISSUE THREAD

**Issue by ZekeZDev** [EmilsGithub/Clutter-Mod-Repository#31]
Hi, I am currently working on a compatiblity mod for this with other mods and I have noticed that cherry_chair is not in the flammable.json

This means that cherry chairs are fireproof.

**Comment by ZekeZDev** [comment]
actually none of the cherry items are in this file.

**Comment by EmilsGithub** [comment]
You're right, thanks for reporting, found out that I had not added bamboo either. 😆
Will be fixed in the next update.
