### ISSUE TITLE
[BUG] Possible hard crash when interacting with players by right clicking.

### ISSUE THREAD

**Issue by wrsgwergergwer** [EmilsGithub/Clutter-Mod-Repository#35]
https://pastebin.com/qSi36Xbp
When attempting to right click on a player while crouching the game instantly crashes. Im guessing this is tied to the petting feature this mod adds, not really code savy enough to check that myself.

**Comment by EmilsGithub** [comment]
Hi, thanks I am aware of this issue and will patch it either today or tomorrow.
