### ISSUE TITLE
[Suggestion] Reskinned Cardboard Box called Gift Box

### ISSUE THREAD

**Issue by wrsgwergergwer** [EmilsGithub/Clutter-Mod-Repository#36]
As title says, identical functionality but simply reskinned to look like a wrapped gift, perhaps ability to dye it?

**Comment by EmilsGithub** [comment]
Hi, I added this in 0.5.3, which released December 18th.. Although the "present" I released has just 1 slot. Currently there's only a red version but I might add more.
