### ISSUE TITLE
[Bug] Log spam from `net.emilsg.clutter.world.spawner.NetherAnimalSpawner`

### ISSUE THREAD

**Issue by unilock** [EmilsGithub/Clutter-Mod-Repository#37]
As of version 0.5.4, while in the Nether, a single number is constantly printed to the game's log - any of `0`, `1`, `2`, etc.

I believe this is due to the following (debug?) line in `net/emilsg/clutter/world/spawner/NetherAnimalSpawner` (found via [BadStdOut](https://modrinth.com/mod/badstdout) + decompilation):

```java
System.out.println(passiveMobCount);
```

That probably shouldn't be there.

**Comment by EmilsGithub** [comment]
Thanks, I will patch this right away.
