### ISSUE TITLE
[BUG] Clash with new Necrosis Enchantment and BetterNether Cactus

### ISSUE THREAD

**Issue by GeekyBakerBen** [EmilsGithub/Clutter-Mod-Repository#38]
Minecraft 1.20.1
Fabric 0.15.33
Clutter 0.5.6
BetterNether 9.0.10

Just updated to the 0.5.6 version of Clutter, and during play it seems a mob has died to a cactus (in this instance, specifically the Nether Cacti from Better Nether, but I don't know if the same result would come from a vanilla Minecraft cactus death too), and then crashed with the following crash report:

[crash-2024-01-04_20.42.53-server.txt](https://github.com/EmilsGithub/Clutter-Mod-Repository/files/13835391/crash-2024-01-04_20.42.53-server.txt)

Can't claim to understand it, but it does mention the new Necrosis from Clutter, so....here I am.

**Comment by EmilsGithub** [comment]
Pretty sure that was fixed in 0.5.7 which released last night, but do confirm if it's still happening after you update.
