### ISSUE TITLE
Strange visual glitch in latest update

### ISSUE THREAD

**Issue by gamerpotion** [EmilsGithub/Clutter-Mod-Repository#4]
Upgrading to clutter-1.20.1-0.3.9.jar
and then playing on servers that use clutter-1.20.1-0.3.8.jar
results in visual glitches which seem to be using random items even from Regions Unexplored mod. Havent experienced this before

Before:
<img src="https://media.discordapp.net/attachments/1003407908463190073/1126998961081815060/image.png" />

After:
<img src="https://media.discordapp.net/attachments/1003407908463190073/1126997542043918449/image.png" />

<img src="https://media.discordapp.net/attachments/1127037617817530378/1127037618136305746/Minecraft_Screenshot_2023.07.07_-_17.41.25.92.png" />

**Comment by EmilsGithub** [comment]
Does the client and server have the exact same mods?

**Comment by gamerpotion** [comment]
hi, yes just clutter mod that the versions mismatch, so its a really strange one

**Comment by gamerpotion** [comment]
Players are reporting visual glitch items being replaced by items from this mod - https://www.curseforge.com/minecraft/mc-mods/regions-unexplored

is there a conflict between clutter and that by any chance?

**Comment by EmilsGithub** [comment]
Is it in a modpack or something? Don't see why clutter would be incompatible with regions unexplored.

**Comment by EmilsGithub** [comment]
Oh nevermind, you really should use the same version on both servers and the client.

**Comment by gamerpotion** [comment]
hi, yes Clutter is included in my modpack - https://www.curseforge.com/minecraft/modpacks/darkrpg
its really strange the recent update this started happening

**Comment by EmilsGithub** [comment]
Just make sure that the client and server are running the same version of the mod then you should be good.🙂

**Comment by gamerpotion** [comment]
> Just make sure that the client and server are running the same version of the mod then you should be good.🙂

also, would your mod affect chests not joining,  gif below

https://media.discordapp.net/attachments/1077294784877695017/1127767695866200074/javaw_NIMXuX83BV.gif

**Comment by EmilsGithub** [comment]
Haven't touched anything that should be changing the way chests are rendered.

**Comment by gamerpotion** [comment]
ok thanks, just checking all the mods incase something was causing it.
