### ISSUE TITLE
Shelf Displays Things Backwards

### ISSUE THREAD

**Issue by PastellePixie** [EmilsGithub/Clutter-Mod-Repository#41]
![2023-10-19_16 31 14](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/71416115/eebe267d-21c2-4105-99f6-d456583e65a5)

I've been using the shelves to display plushies from other mods but they all face the wall. :(

Fabric 1.20.1 (15.3)

**Comment by EmilsGithub** [comment]
Hi, which mods specifically? Do other things from other mods also display this way or just the plushies?

**Comment by PastellePixie** [comment]
Perfect Plushies, Plushables, Practical Plushies, Plushie Mod

 Yep, things from other mods are either sideways or backwards.

**Comment by EmilsGithub** [comment]
![2024-01-17_20 31 41](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/88748435/332203c6-54f8-47b3-9ac0-a25ec3ef3b2c)
Will be fixed in the next major update.
