### ISSUE TITLE
[BUG] Elytra Mods incompatibilities

### ISSUE THREAD

**Issue by peow** [EmilsGithub/Clutter-Mod-Repository#42]
with Clutter update 0.5.6 and 0.5.7 it is now possible to use a Butterfly Elytra in Trinket's Cape Slot, and this is incredible, but some problems came with it
some mods have not worked as they should and I will list some here

I made a video demonstrating the incompatibilities, and as I write the report here, I will say in which minute of the video this problem occurs, for example: "__(1:25)__"

video link - https://www.youtube.com/watch?v=4JxgOSaQK4c

1) **Elytra Physics** is a visual-only mod, which makes Elytra move when you walk or run, at the beginning the mod only worked with  Vanilla Elytra, but with the v2.0 update it brought greater compatibility, built in compatibility with several mods, and if a mod doesnt works you can configure the Elytra Physics adding the desired Elytra "classpath", and thus Elytra Physics recognizes it, but this was not necessary since Butterfly Elytra is already recognized by default, so using Elytra Physics 2.0 with Clutter 0.5.**5** (before the Butterfly Elytra Trinket Update) everything worked correctly, you just couldn't equip the Butterfly Elytra into the Cape Slot

However, with the Clutter 0.5.6 and 0.5.7 update, things became problematic, Vanilla Elytra still receives the Physical effect, but Butterfly Elytra does not (without using Trinkets, just the Chestplate Slot)
using Elytra Physics with Clutter 0.5.**5** + Trinkets and Elytra Slot, the Vanilla Elytra received the Physics effect in both the Chestplate and the Cape Slot, and the Butterfly Elytra received the effect in the Chestplate Slot __(0:14)__, (but it was not possible to equip it in the Cape Slot)

When using Elytra Physics with Clutter 0.5.**7** + Trinkets (but without Elytra Slot mod, depending only on Clutter to place Elytras in the Cape Slot), Vanilla Elytra is no longer affected by Elytra Physics in the Cape Slot __(1:19)__, only in the Chestplate Slot, and Butterfly Elytra is not affected in any way, in any slot, which I can't understand, logically it should at least work in the Chestplate slot, just as it was in version 0.5.**5**

The biggest oddity comes now, when using Elytra Physics with Clutter 0.5.**7** + Trinkets + Elytra Slot, the Vanilla Elytra renders 2 times when it is in the Cape Slot __(1:41)__, both the standard static version and the version with physics, I imagine that Clutter renders static Elytra, and Elytra Slot renders the Elytra with physical effect; while the Butterfly Elytra continues static in any situation

Elytra Physics allows you to add an Elytra "classpath" from a mod to add compatibility with it, but I'm not smart enough to find the Butterfly Elytra classpath to test if this would solve the problems
![image](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/613f7dad-cb78-4a39-a3b4-869c196758b4)

these problems make the user has only 2 options: remove Elytra Physics or use Clutter 0.5.**5** (so without being able to equip Butterfly Elytras on Cape Slot), which is sad

-----------------------

2) **Elytra Time** __(2:18)__ - this mod makes an assumption about how much time is left until your Elytra completely runs out of durability, making a calculation based on the damage it has already received, and if it has Unbreaking, the mod previously only worked with the Chestplate Slot, but version v2.0.0 came with support for the Trinket API, however the mod cannot detect the Butterfly Elytra in the Trinket's Cape Slot, unlike the Elytra Slot mod does with Vanilla Elytra

Elytra Time allows you to see how much time is left for Elytra to end when you select the Elytra and see her Tooltip __(2:22)__, or when you press F4 while wearing an Elytra __(2:31)__, so a message appears in the chat informing you of the remaining time, however when you are not using an Elytra and press F4, an error message appears in the chat, and this message appears when trying to press F4 using the Butterfly Elytra in the Cape Slot __(2:57)__, which I can't understand since the mod is compatible with the Trinket API, and not directly with the Elytra Slot
![image](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/69a7ae06-4326-45f1-8748-7293916fe4e7)

---------------

3) **Elytra Trims** __(3:12)__ - this mod allows you to add Trims to Elytras, in addition to also dyeing them or combining them with a Banner;
after version 2.0.0, the mod promises compatibility with all mods that add Elytras, I believe that through some global configuration
![image](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/6233786e-b953-49e5-8ef3-06760732343e)

 but it never worked with Clutter's Elytras (even on old Clutter versions), I don't know if this can be resolved by you, if not please tell me, so I will report this problem to them
When Trimming a Butterfly Elytra __(3:20)__, nothing changes visually, the same happens when trying to dye it __(3:58)__ or combining with a Banner __(4:27)__ , but the most relevant thing is the fact that you can't even see the Trims on it.

------------

**Screenshots**
![image](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/9b4dae09-cfb6-4459-8266-6911a9880d17)

**Mods Versions:**
"Clutter 1.20.(0-1)-0.5.7"
"Elytra Physics 2.0"
"Elytra Time 2.0.0"
"Elytra Trims 2.0.0-beta.4"
"Trinkets 3.7.1"
"Elytra Slot 6.3.0+1.20.1"
"GeckoLib 4.4.2"
"Fabric API 0.91.0+1.20.1"

*my log if needed - 
[latest.log](https://github.com/EmilsGithub/Clutter-Mod-Repository/files/14325320/latest.log)

----------

**Additional context**

Im playing in Fabric **1.20.1**, with Fabric Loader **0.14.22**, if is possible to fix these issues pls make an update to this version

**Comment by EmilsGithub** [comment]
Hi, thanks for the great bug/compatibility report!

Elytra Physics not working was an easy fix.

From what I can find, Elytra time **_specifically_** looks for the normal elytra in the trinkets slot so this would have to be fixed on their end. - I made a pull request with changes that would fix this, they just have to approve.

Elytra Trims, took some more time but fixed as well. Had to contact the mod dev for help, which they happily provided.

**Comment by peow** [comment]
this is great news, thanks <3

**Comment by peow** [comment]
I found another bug
When your skin has a cape and you equip an Elytra, the normal thing to happen is that the Elytra replaces the cape, taking its texture, however, when placing it in the Trinket's cape slot, both the elytra and the cape are rendered.

Cape:
![2024-02-26_22 04 42](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/2a6c4744-dce6-4a8a-94b2-25c4b16fc094)

Using Chestplate Slot:
![2024-02-26_22 05 06](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/413f8079-99b1-4073-8785-d8ecd16af83b)

Using Cape Slot from Trinket (Clutter 0.5.7)
![2024-02-26_22 04 37](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/c8e00e5a-98f7-4c18-b1a8-4a51c59394a5)

-------------------

doing tests I saw that the same does not happen while using Cape Slot with Elytra Slot mod (without Clutter)
![2024-02-26_22 14 00](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/26c00307-736e-40d2-8e8d-695bdb66c85f)
