### ISSUE TITLE
[QUESTION] Where does Onyx spawn?

### ISSUE THREAD

**Issue by EnderGirl1500** [EmilsGithub/Clutter-Mod-Repository#44]
Just as the title says, I just want to know where to find onyx since JER doesn't show.

**Comment by EmilsGithub** [comment]
Onyx Geodes in The Nether. They work the same as Amethyst Geodes.
Please don't post questions as issues, that can be done in the Discord.

FYI there is a wiki.
https://clutter.fandom.com/wiki/Clutter_Wiki

In your case:
https://clutter.fandom.com/wiki/Biomes_and_Worldgen#Geodes
