### ISSUE TITLE
[BUG]? Penguin Breeding

### ISSUE THREAD

**Issue by NDracorex** [EmilsGithub/Clutter-Mod-Repository#45]
**Describe the bug**
A clear and concise description of what the bug is:
         If you confine a penguin in too small of a space, it will NEVER lay its egg. 

**To Reproduce**
If applicable please add the steps to reproduce the behavior:
        Capture 2 penguins. Place them in a small are or really any enclosed area (I'm having issues with a 30x30 area)  and breed. 
        They WILL NOT lay eggs for quite some time, and sometimes never lay the egg at all.

**Mod Version:**
 Example: "Clutter 1.20.(0-1)-0.5.7"
                clutter-1.20-0.5.7.jar

**Comment by EmilsGithub** [comment]
Penguins require specific blocks to lay their eggs on, I am currently unable to check all of them but I know grass blocks and snow are on there.
