### ISSUE TITLE
[BUG] Hats being rendered in first person (First-person Model & Trinkets)

### ISSUE THREAD

**Issue by peow** [EmilsGithub/Clutter-Mod-Repository#47]
**Describe the bug**

When using the First-person Model with Clutter, when equipping a hat in the trinket slot, the hat is rendered in first person, obstructing the view

**Screenshots**
* using the Trinket slot:

![2024-04-25_12 55 21](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/b25eb5c8-4010-4014-9f55-a1d21b992823)

![2024-04-25_12 43 55](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/ca72602a-206f-4b85-a919-c7727394bb1e)

-----------------

* using the Vanilla Helmet slot (work as expected)

![2024-04-25_12 44 18](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/4596ce6f-8eda-4fcb-bc7f-6fa7fdef7233)

![2024-04-25_12 44 21](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/af336c72-d462-4b8d-98fa-810f8c58ba79)

---------------

This is a common problem to happen, apparently it is the mod that adds the accessories (in this case the Clutter mod) that needs to change the code so that the accessory is not rendered when equipped in the Trinket slot while you are in first person, only in third person

check this Issue where the creator talks a bit about this:
https://github.com/tr7zw/FirstPersonModel/issues/385

**Mod Version:**
 "Clutter 1.20.(0-1)-0.5.7"
 "First-Person Model 2.3.4"
 "Trinkets 3.7.2"

If it is possible to add compatibility I would love to have an update to **1.20.1**

**Comment by EmilsGithub** [comment]
Hi, thanks for pointing this out, it was an easy fix. 
This will be released with the 0.6.0 update, which will be for 1.20.1 (which is currently the main version of Clutter).

**Comment by peow** [comment]
thanks
