### ISSUE TITLE
[BUG] Butterfly Elytras unrepairable

### ISSUE THREAD

**Issue by ShadowSShifter** [EmilsGithub/Clutter-Mod-Repository#48]
**Describe the bug**
A clear and concise description of what the bug is: When attempting to repair a butterfly elytra, it will not create a repaired version after using a phantom membrane. There is also no other listed way to repair them via JEI.

**To Reproduce**
If applicable please add the steps to reproduce the behavior:

1. Obtain a low-durability Warped Butterfly Elytra and phantom membrane
2. Go to an anvil and add both into anvil to repair as normal
3. There will be no resulting item (repaired elytra)

**Screenshots**
![Screenshot (107)](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/64106541/078cae73-bf90-4568-b9aa-771c4428ceb7)

**Mod Version:**
 Example: "Clutter 1.20.(0-1)-0.5.7": Version is clutter-1.20-0.5.7

**Additional context**

**Comment by EmilsGithub** [comment]
Hi, not a bug. Butterfly Elytra can only be repaired with their respective bottled butterfly.

In your case you should use a "warped butterfly in a bottle".
