### ISSUE TITLE
[BUG] Crimson Newts ignoring spawn cap

### ISSUE THREAD

**Issue by notcorin** [EmilsGithub/Clutter-Mod-Repository#49]
**Describe the bug**
Crimson Newts are ignoring spawn cap causing major lag.

**To Reproduce**
Go near the crimson forest biome at the nether roof wait about 10 minutes.

**Mod Version:**
clutter-1.20-0.5.8 - Fabric

![2024-06-05_14 15 08](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/54869255/ae5ea182-be6c-4f0c-8b23-f377931bdc2f)

All the yellow dots are entities.

**Comment by EmilsGithub** [comment]
Should be resolved, made them despawn if there are no players nearby, and if they are not set to be persistent by any vanilla methods, (breeding, name tags, boats etc). You might still have to dispatch the old ones though...
