### ISSUE TITLE
typo in Dark Oak Mosaic name

### ISSUE THREAD

**Issue by peow** [EmilsGithub/Clutter-Mod-Repository#50]
![2024-06-16_16 34 29](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/c60d9acf-7fc2-499a-adc9-37853a2148e7)

the name of the block is written "Darl" instead of "Dark"

clutter 0.5.9

**Comment by EmilsGithub** [comment]
Thanks for pointing this out, will be fixed in the next update.
