### ISSUE TITLE
[BUG] remaining incompatibilities with Elytra Trims

### ISSUE THREAD

**Issue by peow** [EmilsGithub/Clutter-Mod-Repository#51]
after the latest updates the Butterfly Elytras no longer receive Trims, and that's a good thing

![image](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/12c6335b-01fc-4241-8b9d-6b3fe2821e21)

however it is still possible to color them and add banners to them, which causes the Butterfly Elytras to lose their texture, this should also be prevented

![image](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/e7bbd49a-80c8-4634-ace3-0d444498c864)
![2024-06-19_09 06 49](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/e1fe9894-a294-4613-afe7-f803d5609188)
![2024-06-19_09 07 24](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/588b817e-c950-40d2-b3e5-35354fb5230c)

![image](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/083c9b9b-5303-4d71-a39b-526c8ef0d97a)
![2024-06-19_09 09 06](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/9df8937f-5382-4832-b238-3a330c700c1b)

----------------

* another problem is Elytras with modifications (Trim, dye or banner) get the default texture when they are equipped in the Trinkets Cape Slot

![image](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/9769a7e0-04f2-41a0-be20-a812837fa66b)
![image](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/f058d5a0-76f8-46d9-bcc0-1cc3e693d159)
![image](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/b8cd05d0-310b-4175-9ab9-0343b1cec308)
![image](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/3f14858d-3e70-4aac-b85f-cd2764f9d09c)

and when using Clutter and Elytra Trims together with the "**Elytra Slot**" mod, the modified **Vanilla** Elytras appear correctly in the Cape Slot

![image](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/4010f518-7c9e-4157-9efe-6ee75a42fce0)
![image](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/0fc63c4c-46ea-4586-887d-38a71369daec)

(but the colored **Butterfly** Elytras and with banners still have they default texture)
![image](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/4f8f8394-5ea4-4334-94e6-eda0bba96e24)
![image](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/0e7d7ed8-0bfe-43e3-9452-4e26ea52ce80)

but the **Vanilla** Elytras with some modification (Trim, Banner, Dye) have z-fighting when equipped in the Cape Slot, which is quite noticeable while you're flying, but you can also see it when you crouch

![2024-06-19_09 24 03](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/6ead7c68-4493-45ad-92d1-2f8ab88545f7)
*look at the left wing*

![2024-06-19_09 32 39_3](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/89d445d3-4e76-4ea5-a03c-670fa7e81a4b)
*Pink Vanilla Elytra*

![2024-06-19_09 37 03](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/50d212af-3002-49d8-b2a9-8aaa36f4024b)
![2024-06-19_09 37 03_2](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/105888751/274e2284-c442-4c05-a693-aad3cf47e199)
*Vanilla Elytra with Banner*

My theory is that the Elytras are being rendered twice, once by the Elytra Slot and once by the Clutter, the Z-Fighting problem stops when you disable Clutter and leave only Elytra Trims and Elytra Slot enabled

**Mod Version:**
Clutter 1.20.(0-1)-0.5.9
Elytra Trims 3.2.0
Trinkets 3.7.2
Elytra Slot 6.4.0

Fabric 1.20.1

if it's possible to fix these problems, pls let the fix come in one of the next 1.20.1 updates, thanks

**Comment by luigistyle** [comment]
Can confirm, any fixes would be appreciated ❤️

**Comment by EmilsGithub** [comment]
The Elytras not being trimmable should have been fixed in the 3.4.0 update for Elytra Trims.
The Elytra being rendered twice will be fixed soon™.

**Comment by EmilsGithub** [comment]
Will be fixed in 0.6.0
