### ISSUE TITLE
Suggestion: Bottle decorations that work like Candles

### ISSUE THREAD

**Issue by slavens** [EmilsGithub/Clutter-Mod-Repository#53]
At the moment, I haven't seen a mod that has bottles for decorations, and certainly nothing that lets them be placed like candles. What I'm hoping for is bottles that can be placed as decorations and right-clicking continues to add to the number of bottles placed on top a block. 

It would be nice to have single and multi-colored 'collections' of bottles in both similar and random sizes. Think of bottles behind the counter at a bar/pub or the mess in a medicine cabinet.

If you really wanted to out-do yourself, it would be cool to have similar decorations for "lab glass" like flasks and beakers...

**Comment by EmilsGithub** [comment]
Some bottles have already been made for 0.6.0 but I don't see an issue adding some more before it's released. Flasks sound great as s well.
