### ISSUE TITLE
[Compatibility Issue] Meltdown Potion Effect's mixin is probably causing other modded explosions to act like it

### ISSUE THREAD

**Issue by f-raZ0R** [EmilsGithub/Clutter-Mod-Repository#55]
**What is the compatibility issue**
I can't tell _what_ exactly is causing this, due to the project being closed source, but from extensive testing, I've worked out that clutter is causing explosions that would normally produce primordial fire in spectrum, to instead produce regular fire. This works perfectly fine with just spectrum, but adding clutter breaks this. I _think_ this would also affect other modded explosions?

**Additional info**
-The most likely explanation for why this happens , in my opinion, is that something about the Meltdown potion effect is completely overwriting spectrum's explosion, due to both being explosions that also produce fire.
-This is on fabric, 1.20.1

**Screenshots**
What an incandescent amalgam explosion looks like with, and without Clutter being installed: (note the lack of the special fire with clutter, and also im pretty sure that with clutter the explosion is a lot smaller?)
![2024-08-12_20 12 56](https://github.com/user-attachments/assets/c6637e0b-26b0-446d-b7ae-cfb26896c14c)
![2024-08-12_20 18 15](https://github.com/user-attachments/assets/9cf50710-6991-4efa-979a-30ae3a208fdf)

**Comment by EmilsGithub** [comment]
It's most likely caused by Clutter adding green "copper fire", not by the meltdown effect. I'll have a look at it after work today.

**Comment by EmilsGithub** [comment]
Found the issue, a patch will be out shortly. (Before the weekend at least)
![2024-08-13_23 30 44](https://github.com/user-attachments/assets/46d1952f-410d-4198-bdee-64047f81ad35)
