### ISSUE TITLE
[Compatibility Issue] Cannot access the field due to Private ENUM

### ISSUE THREAD

**Issue by Xelbayria** [EmilsGithub/Clutter-Mod-Repository#57]
### What is the compatibility issue
Take a look at [WoodenBenchBlock](https://github.com/EmilsGithub/Clutter-Mod-Repository/blob/fbb6053d046cc1512283d28a0c88a21764f0657e/src/main/java/net/emilsg/clutter/block/custom/WoodenBenchBlock.java#L132)

the `LegPosition` ENUM is set to "private", I've checked other blocks (Chairs & Tables), their ENUM are all public. 

SOLUTION: it's simple, you can change it to public and upload the newer version to Curseforge. I can use that mod to finish the support (more details below)

The version for 1.20.1 is v0.5.10. 

### Additional info
I'm adding support to Clutter mod via Every Compat, so you don't have to worry about the addon to support other wood mods (Biomes O' Plenty, and more...).

**Comment by EmilsGithub** [comment]
I'll release a quick patch for it sometime this week, let me know if there is anything else you need access to in the meantime.

**Comment by Xelbayria** [comment]
thanks for the replying. The change of that "private" to "public" is all I need for now.

**Comment by EmilsGithub** [comment]
I updated the mod, give it some time to approve on CurseForge and you should be gtg.

**Comment by Xelbayria** [comment]
All good now. Thanks for the quick changes. Your mod will be supported by EveryCompat

**Comment by Xelbayria** [comment]
Forgot to ask you, can you do the same for 1.19.2?
