### ISSUE TITLE
Missing model for variant (Clutter 1.20.1)

### ISSUE THREAD

**Issue by gamerpotion** [EmilsGithub/Clutter-Mod-Repository#6]
Seeing chunks of errors in logs when playing, please see below

https://pastebin.com/tBSAywdL

**Comment by gamerpotion** [comment]
Full latest.log - https://pastebin.com/DVGsYYa5
starting game up and can see from line 699 onwards

**Comment by EmilsGithub** [comment]
I'll look into it. Basically all those erros don't really do anything because most of them are just the blockstate saying it's missing a model for the waterlogged state (which is the same as the regular model....).
