### ISSUE TITLE
Clutter bunk bed zfighting

### ISSUE THREAD

**Issue by generrosity** [EmilsGithub/Clutter-Mod-Repository#7]
Hello!

Something my players notices is that the bunkbed has a decent amount of zfighting going on. Using the freshes builds from Modrinth, 1.20.1 Fabric/Quilt with homebrew pack.

The two that I notice is the top surface of the foot of the bed (looks like the texture is rotated 180 degrees)
![image](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/12838061/b3350512-a044-4cb9-bfd1-a81ebc9d5756)

and all around the outside (which at a guess is stretched texture as some of the middle pixels pattern look not to move). I can see some of the peeling affect on the 'feet' of the bed too which I hope doesn't mean that its a mod mismatch on our end?

![image](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/12838061/51dcb27d-7dbe-4ada-a898-7c7ac193fde0)
![image](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/12838061/df480214-9e31-4979-a351-7f449f8a1eba)

**Comment by EmilsGithub** [comment]
Are you using another mod that affects beds in any way?

**Comment by generrosity** [comment]
No, as far as any of us can tell, we dont have anything that changes modifies or adds beds in any way, sorry

**Comment by EmilsGithub** [comment]
Forgot about this issue, could you provide a mod list for this modpack?

**Comment by generrosity** [comment]
Since recent updates, we don't seem to be having this problem any longer. Strange that the texture would shift around. Thanks for considering and thinking of how it might have applied tho, much appreciated
