### ISSUE TITLE
Butterflies performance issues

### ISSUE THREAD

**Issue by VaffanClash** [EmilsGithub/Clutter-Mod-Repository#8]
Hello, I recently added this mod to my server. One of my friends lives pretty far away from me, and her internet connection isn't the best, so I ran some tests and I found this:
<img width="455" alt="image" src="https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/52460508/5b4ef1cb-25cb-45e6-922f-d35a8e34a426">
Now, I'm not an expert with minecraft performance, neither in Java, even tho I'm a JavaScript developer. Seeing this error, it's obvious that there is something wrong with butterflies, so I tried turning them off in the config.
The config presents this line: `spawn.butterflies=true`, which is apparently a Boolean, so I just changed it to `false`, but the butterflies are still here. I also tried checking the source code but well, not being a Java developer I couldn't figure out much.

Is there actually anything wrong with butterflies? And can it be related to internet connection issues?

**Comment by EmilsGithub** [comment]
I'll take a look at the butterfly code. How exactly does the config file look?

**Comment by VaffanClash** [comment]
<img width="497" alt="image" src="https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/52460508/cf223939-153f-409f-b264-76e45ed53790">

This is exactly what it looks like now. Also, the file name is "clutterconfig.properties" tho. Is it correct?

**Comment by EmilsGithub** [comment]
And that's the file on the server?

**Comment by VaffanClash** [comment]
> And that's the file on the server?

Yes, exactly. Sorry for the late answer

**Comment by EmilsGithub** [comment]
Did you also restart the server?

**Comment by VaffanClash** [comment]
> Did you also restart the server?

Yeah exactly

**Comment by EmilsGithub** [comment]
Weird that they're still spawning with the config set to false, pretty sure I checked that. 
Also, I've changed the way butterflies pathfind to (hopefully) increase performance. This will be changed in the next update.
Lastly, what did you use to get those performance numbers?

**Comment by VaffanClash** [comment]
> Weird that they're still spawning with the config set to false, pretty sure I checked that. Also, I've changed the way butterflies pathfind to (hopefully) increase performance. This will be changed in the next update. Lastly, what did you use to get those performance numbers?

Nice! I used the mod Spark to get all the results
