### ISSUE TITLE
chameleon invisble

### ISSUE THREAD

**Issue by rainysux** [EmilsGithub/Clutter-Mod-Repository#9]
![2023-07-15_22 57 48](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/113203852/1b213364-0f18-491c-9b72-eba6409c2fe9)
![2023-07-15_22 57 50](https://github.com/EmilsGithub/Clutter-Mod-Repository/assets/113203852/a4126568-4a0a-44ac-88ff-58eceb717a47)

Possibly just incompatible with my shader pack, havent tried others. 
[OverimaginedShaders_r1.2.1-1.0.zip](https://github.com/EmilsGithub/Clutter-Mod-Repository/files/12063400/OverimaginedShaders_r1.2.1-1.0.zip)
This is my shaders
fabric 1.20

**Comment by EmilsGithub** [comment]
Yeah, it's a geckolib incompatibility. Planning on ditching it later but nothing I can do about it right now.
